config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/RECETOX/recetox-aplcms:
      branch: master
      repo: https://github.com/RECETOX/recetox-aplcms
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/RECETOX/recetox-aplcms git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-russet-audemer.sh
        container: qc.acc_bluesy-ultramarine-numbat
  QC.Doc:
    repos:
      github.com/RECETOX/recetox-aplcms find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-grey-emu.sh
        container: qc.doc_wimpy-tangerine-tuatara
      github.com/RECETOX/recetox-aplcms git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-mauve-mole.sh
        container: qc.doc_slaphappy-russet-discus
      github.com/RECETOX/recetox-aplcms markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cerulean-okapi.sh
        container: qc.doc_woolly-chartreuse-burmese
  QC.Lic:
    repos:
      github.com/RECETOX/recetox-aplcms licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-vermilion-eagle.sh
        container: qc.lic_gloppy-flax-hamster
  QC.Sty:
    repos:
      github.com/RECETOX/recetox-aplcms hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-magenta-millipede.sh
        container: qc.sty_ugly-chartreuse-echidna
      github.com/RECETOX/recetox-aplcms jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-apricot-cow.sh
        container: qc.sty_lumpy-viridian-turtle
  QC.Ver:
    repos:
      github.com/RECETOX/recetox-aplcms get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-razzmatazz-rattlesnake.sh
        container: qc.ver_snazzy-burgundy-vole
timeout: 1800
