config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/RECETOX/recetox-aplcms:
      branch: master
      repo: https://github.com/RECETOX/recetox-aplcms
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/RECETOX/recetox-aplcms git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-wisteria-urchin.sh
        container: qc.acc_randy-cardinal-squid
  QC.Doc:
    repos:
      github.com/RECETOX/recetox-aplcms find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-ruby-rat.sh
        container: qc.doc_freaky-white-akita
      github.com/RECETOX/recetox-aplcms git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-malachite-abyssinian.sh
        container: qc.doc_goopy-wisteria-worm
      github.com/RECETOX/recetox-aplcms markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-khaki-lynx.sh
        container: qc.doc_homely-platinum-lizard
  QC.Lic:
    repos:
      github.com/RECETOX/recetox-aplcms licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-charcoal-dog.sh
        container: qc.lic_nerdy-teal-binturong
  QC.Sty:
    repos:
      github.com/RECETOX/recetox-aplcms hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-tan-hummingbird.sh
        container: qc.sty_flimsy-dandelion-dormouse
      github.com/RECETOX/recetox-aplcms jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-plum-chinook.sh
        container: qc.sty_skinny-lime-wolfhound
  QC.Ver:
    repos:
      github.com/RECETOX/recetox-aplcms get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-razzmatazz-shrimp.sh
        container: qc.ver_paltry-bistre-flounder
timeout: 1800
